/* tslint:disable */
/* eslint-disable */
/**
 * BackendMdViewer
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface ApiMarkdownBeautifyPostRequest {
    /**
     * 
     */
    body?: string;
}

export interface ApiMarkdownFileNameDeleteRequest {
    /**
     * 
     */
    fileName: string;
}

export interface ApiMarkdownFileNameGetRequest {
    /**
     * 
     */
    fileName: string;
}

export interface ApiMarkdownFileNamePutRequest {
    /**
     * 
     */
    fileName: string;
    /**
     * 
     */
    file?: Blob;
}

export interface ApiMarkdownUploadPostRequest {
    /**
     * 
     */
    file?: Blob;
}

/**
 * 
 */
export class MarkdownApi extends runtime.BaseAPI {

    /**
     * Creates request options for apiMarkdownAllFilesGet without sending the request
     */
    async apiMarkdownAllFilesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Markdown/allFiles`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiMarkdownAllFilesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        const requestOptions = await this.apiMarkdownAllFilesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiMarkdownAllFilesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.apiMarkdownAllFilesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiMarkdownBeautifyPost without sending the request
     */
    async apiMarkdownBeautifyPostRequestOpts(requestParameters: ApiMarkdownBeautifyPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/Markdown/beautify`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        };
    }

    /**
     */
    async apiMarkdownBeautifyPostRaw(requestParameters: ApiMarkdownBeautifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.apiMarkdownBeautifyPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async apiMarkdownBeautifyPost(requestParameters: ApiMarkdownBeautifyPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiMarkdownBeautifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for apiMarkdownFileNameDelete without sending the request
     */
    async apiMarkdownFileNameDeleteRequestOpts(requestParameters: ApiMarkdownFileNameDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling apiMarkdownFileNameDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Markdown/{fileName}`;
        urlPath = urlPath.replace('{fileName}', encodeURIComponent(String(requestParameters['fileName'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiMarkdownFileNameDeleteRaw(requestParameters: ApiMarkdownFileNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiMarkdownFileNameDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMarkdownFileNameDelete(requestParameters: ApiMarkdownFileNameDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMarkdownFileNameDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiMarkdownFileNameGet without sending the request
     */
    async apiMarkdownFileNameGetRequestOpts(requestParameters: ApiMarkdownFileNameGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling apiMarkdownFileNameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/Markdown/{fileName}`;
        urlPath = urlPath.replace('{fileName}', encodeURIComponent(String(requestParameters['fileName'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async apiMarkdownFileNameGetRaw(requestParameters: ApiMarkdownFileNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiMarkdownFileNameGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMarkdownFileNameGet(requestParameters: ApiMarkdownFileNameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMarkdownFileNameGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiMarkdownFileNamePut without sending the request
     */
    async apiMarkdownFileNamePutRequestOpts(requestParameters: ApiMarkdownFileNamePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fileName'] == null) {
            throw new runtime.RequiredError(
                'fileName',
                'Required parameter "fileName" was null or undefined when calling apiMarkdownFileNamePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/Markdown/{fileName}`;
        urlPath = urlPath.replace('{fileName}', encodeURIComponent(String(requestParameters['fileName'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiMarkdownFileNamePutRaw(requestParameters: ApiMarkdownFileNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiMarkdownFileNamePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMarkdownFileNamePut(requestParameters: ApiMarkdownFileNamePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMarkdownFileNamePutRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for apiMarkdownUploadPost without sending the request
     */
    async apiMarkdownUploadPostRequestOpts(requestParameters: ApiMarkdownUploadPostRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/api/Markdown/upload`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async apiMarkdownUploadPostRaw(requestParameters: ApiMarkdownUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.apiMarkdownUploadPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiMarkdownUploadPost(requestParameters: ApiMarkdownUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiMarkdownUploadPostRaw(requestParameters, initOverrides);
    }

}
